### ISSUE TITLE
engine.js line 170 crashInfo; changeto //crashInfo;

### ISSUE THREAD

**Issue by hillsta89** [AxelConceicao/bustabit-script-simulator-2020#1]
Love your work, as it was no script would work intially my fix was removing crashInfo; from the engine code. Was throwing..

Cleaning...
'tests/100.txt' cleaned (100 games and 1 invalid lines)
Merging...
'scripts/LightGuide.js' merged
Starting...
/home/server/bbsim/.temp/script.js:183
  crashInfo;
           ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

Incase anyone else having the same issues

**Comment by AxelConceicao** [comment]
@hillsta89 That was a typo and I didn't get any error on my machine, so thank you for your feedback!
